export const MOBILE = '(max-width: 767px)'
export const TABLET = '(max-width: 991px)'
export const DESKTOP = '(min-width: 992px) and (max-width: 1023px)'
export const SMALLDESKTOP = '(min-width: 1024px) and (max-width: 1279px)'
export const LARGEDESKTOP = '(min-width: 1280px)'
export const DESKTOP_ALL = '(min-width: 992px)'
export const SMALLDESKTOP_MAX = '(max-width: 1279px)'
